# Generated by Django 6.0.2 on 2026-02-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='The chosen plain-text username used to link data', max_length=150, unique=True)),
                ('streak', models.IntegerField(default=0, help_text='Total days in active streak')),
                ('calories_burned', models.IntegerField(default=0, help_text='Total calories burned today')),
                ('weekly_progress', models.IntegerField(default=0, help_text='A percentage from 0-100 indicating weekly progress')),
            ],
        ),
    ]
