# Generated by Django 6.0.2 on 2026-02-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_achievement_alerts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streakrecord',
            name='worked_out',
        ),
        migrations.AddField(
            model_name='streakrecord',
            name='logged_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text="User's email address", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password', max_length=255, null=True),
        ),
    ]
