# Generated by Django 6.0.2 on 2026-02-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_streakrecord_worked_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Exact internal name of the exercise (e.g., 'bench_press')", max_length=100, unique=True)),
                ('video_file', models.FileField(help_text='The video file for the exercise demonstration', upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
