# Generated by Django 6.0.2 on 2026-03-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='notification_type',
            field=models.CharField(choices=[('MORNING', 'Morning Workout Plan'), ('DIET', 'Diet Suggestion'), ('EVENING', 'Evening Reminder'), ('NIGHT', 'Night Progress Summary'), ('EVENT', 'Event-based Alert')], default='EVENT', max_length=20),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='title',
            field=models.CharField(default='FlexAI Notification', max_length=200),
        ),
    ]
