from django.db import models

class UserProfile(models.Model):
    username = models.CharField(max_length=150, unique=True, help_text="The chosen plain-text username used to link data")
    email = models.EmailField(max_length=255, unique=True, null=True, blank=True, help_text="User's email address")
    password = models.CharField(max_length=255, null=True, blank=True, help_text="Hashed password")
    name = models.CharField(max_length=150, blank=True, null=True, help_text="User's display name")
    profile_image_base64 = models.TextField(blank=True, null=True, help_text="Base64 encoded profile image")
    
    # Basic Stats (Daily & Weekly)
    streak = models.IntegerField(default=0, help_text="Total days in active streak")
    calories_burned = models.IntegerField(default=0, help_text="Total calories burned today")
    weekly_progress = models.IntegerField(default=0, help_text="A percentage from 0-100 indicating weekly progress")
    
    # Global Stats & Info
    age = models.IntegerField(blank=True, null=True)
    height = models.CharField(max_length=20, blank=True, null=True)
    weight = models.CharField(max_length=20, blank=True, null=True)
    total_workouts = models.IntegerField(default=0)
    total_calories = models.IntegerField(default=0)
    active_days = models.IntegerField(default=0)

    # Preferences
    push_notifications = models.BooleanField(default=True)
    workout_reminders = models.BooleanField(default=True)
    achievement_alerts = models.BooleanField(default=True)
    dark_mode = models.BooleanField(default=False)
    
    LANGUAGE_CHOICES = [
        ('English', 'English'),
        ('Tamil', 'Tamil'),
        ('Telugu', 'Telugu'),
        ('Hindi', 'Hindi'),
    ]
    language = models.CharField(max_length=20, choices=LANGUAGE_CHOICES, default='English')

    def __str__(self):
        return f"{self.username} - Streak: {self.streak}"

class WorkoutSession(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='workout_history')
    date = models.DateTimeField(auto_now_add=True)
    workout_type = models.CharField(max_length=100)
    duration_minutes = models.IntegerField(default=0)
    calories_burned = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user_profile.username} - {self.workout_type} on {self.date.strftime('%Y-%m-%d')}"

class StreakRecord(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='streak_records')
    date = models.DateField(auto_now_add=True)
    logged_in = models.BooleanField(default=True)

    class Meta:
        unique_together = ('user_profile', 'date')

    def __str__(self):
        return f"{self.user_profile.username} - {self.date} - {'Active' if self.logged_in else 'Inactive'}"

class AppNotification(models.Model):
    NOTIFICATION_TYPES = [
        ('MORNING', 'Morning Workout Plan'),
        ('DIET', 'Diet Suggestion'),
        ('EVENING', 'Evening Reminder'),
        ('NIGHT', 'Night Progress Summary'),
        ('EVENT', 'Event-based Alert'),
    ]

    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='notifications')
    title = models.CharField(max_length=200, default="FlexAI Notification")
    message = models.TextField(help_text="The notification text to display")
    notification_type = models.CharField(max_length=20, choices=NOTIFICATION_TYPES, default='EVENT')
    scheduled_time = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.notification_type} for {self.user_profile.username}: {self.title}"

class AnalysisRequest(models.Model):
    user_input = models.TextField(help_text="The input text provided by the user for analysis")
    ai_result = models.TextField(blank=True, null=True, help_text="The result generated by the AI")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"AnalysisRequest {self.id} (Created at {self.created_at})"

class ExerciseVideo(models.Model):
    name = models.CharField(max_length=100, unique=True, help_text="Exact internal name of the exercise (e.g., 'bench_press')")
    video_file = models.FileField(upload_to='videos/', help_text="The video file for the exercise demonstration")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class PasswordResetOTP(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='password_reset_otps')
    otp = models.CharField(max_length=6, help_text="6-digit OTP for password reset")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"OTP for {self.user_profile.username} - {self.otp}"

